tmp.dir.path=/tmp

# HDFS
hdfs.namenode.host=127.0.0.1
hdfs.namenode.port=20112
hdfs.namenode.http.port=50070
hdfs.temp.dir=/embedded_hdfs
hdfs.num.datanodes=1
hdfs.enable.permissions=false
hdfs.format=true
hdfs.enable.running.user.as.proxy.user=true
hdfs.datanode.address=127.0.0.1:50010
hdfs.datanode.http.address=127.0.0.1:50075
hdfs.datanode.ipc.address=127.0.0.1:50020

# HDFS Test
hdfs.test.file=/tmp/testing
hdfs.test.string=TESTING

hdfs.namenode.client.host=127.0.0.1
hdfs.datanode.client.address=127.0.0.1:50010
hdfs.datanode.http.client.address=127.0.0.1:50075
hdfs.datanode.ipc.client.address=127.0.0.1:50020