#HADOOP_HOME=/opt/hadoop

tmp.dir.path=/tmp

zookeeper.artifactId=fr.jetoile.hadoop:hadoop-unit-zookeeper:${project.version}
zookeeper.mainClass=fr.jetoile.hadoopunit.component.ZookeeperBootstrap
zookeeper.metadataClass=fr.jetoile.hadoopunit.component.ZookeeperMetadata

hdfs.artifactId=fr.jetoile.hadoop:hadoop-unit-hdfs:${project.version}
hdfs.mainClass=fr.jetoile.hadoopunit.component.HdfsBootstrap
hdfs.metadataClass=fr.jetoile.hadoopunit.component.HdfsMetadata

hivemeta.artifactId=fr.jetoile.hadoop:hadoop-unit-hivemeta:${project.version}
hivemeta.mainClass=fr.jetoile.hadoopunit.component.HiveMetastoreBootstrap
hivemeta.metadataClass=fr.jetoile.hadoopunit.component.HiveMetastoreMetadata

hiveserver2.artifactId=fr.jetoile.hadoop:hadoop-unit-hiveserver2:${project.version}
hiveserver2.mainClass=fr.jetoile.hadoopunit.component.HiveServer2Bootstrap
hiveserver2.metadataClass=fr.jetoile.hadoopunit.component.HiveServer2Metadata

yarn.artifactId=fr.jetoile.hadoop:hadoop-unit-yarn:${project.version}
yarn.mainClass=fr.jetoile.hadoopunit.component.YarnBootstrap
yarn.metadataClass=fr.jetoile.hadoopunit.component.YarnMetadata

maven.central.repo=https://repo.maven.apache.org/maven2/
maven.local.repo=~/.m2/repository

#maven.debug=true

# Zookeeper
zookeeper.temp.dir=/embedded_zk
zookeeper.host=0.0.0.0
zookeeper.port=22010

zookeeper.client.host=127.0.0.1


# Hive
hive.scratch.dir=/hive_scratch_dir
hive.warehouse.dir=/tmp/warehouse_dir

# Hive Metastore
hive.metastore.hostname=0.0.0.0
hive.metastore.port=20102
hive.metastore.derby.db.dir=metastore_db

hive.metastore.client.hostname=127.0.0.1

# Hive Server2
hive.server2.hostname=0.0.0.0
hive.server2.port=20103

hive.server2.client.hostname=127.0.0.1

# Hive Test
hive.test.database.name=default
hive.test.table.name=test_table


# HDFS
hdfs.namenode.host=0.0.0.0
hdfs.namenode.port=20112
hdfs.namenode.http.port=50070
hdfs.temp.dir=/embedded_hdfs
hdfs.num.datanodes=1
hdfs.enable.permissions=false
hdfs.format=true
hdfs.enable.running.user.as.proxy.user=true
hdfs.datanode.address=0.0.0.0:50010
hdfs.datanode.http.address=0.0.0.0:50075
hdfs.datanode.ipc.address=0.0.0.0:50020

# HDFS Test
hdfs.test.file=/tmp/testing
hdfs.test.string=TESTING

hdfs.namenode.client.host=127.0.0.1
hdfs.datanode.client.address=127.0.0.1:50010
hdfs.datanode.http.client.address=127.0.0.1:50075
hdfs.datanode.ipc.client.address=127.0.0.1:50020


# YARN
yarn.num.node.managers=1
yarn.num.local.dirs=1
yarn.num.log.dirs=1
yarn.resource.manager.address=0.0.0.0:37001
yarn.resource.manager.hostname=0.0.0.0
yarn.resource.manager.scheduler.address=0.0.0.0:37002
yarn.resource.manager.resource.tracker.address=0.0.0.0:37003
yarn.resource.manager.webapp.address=0.0.0.0:37004
yarn.use.in.jvm.container.executor=false

yarn.resource.manager.client.address=localhost:37001
yarn.resource.manager.client.hostname=localhost
yarn.resource.manager.scheduler.client.address=localhost:37002
yarn.resource.manager.resource.tracker.client.address=localhost:37003
yarn.resource.manager.webapp.client.address=localhost:37004


# MR
mr.job.history.address=0.0.0.0:37005
mr.job.history.client.address=127.0.0.1:37005


# Docker
docker.imagename=alpine:3.2
docker.exposedports=80
docker.envs=MAGIC_NUMBER:42
docker.labels=MAGIC_NUMBER:42
docker.command=/bin/sh, -c, while true; do echo \"$MAGIC_NUMBER\" | nc -l -p 80; done
docker.fixed.exposedports=21300:80
#docker.classpath.resources.mapping=hadoop-unit-default.properties:/hadoop-unit-default.properties:READ_ONLY

# Docker compose
dockercompose.filename=conf/docker-compose.yml
#dockercompose.exposedports=zoo:2181,resourcemanager:8088
dockercompose.local=false
